player:
  username: admin
  age: 35
  address: 123 Main St
  email: huanhust1998@gmail.com

spring:
  application:
    name: shopdev
  datasource:
    url: jdbc:mysql://localhost:3307/java_spring_boot
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true